# This configuration file is only required when running in sequencing mode.
[Eth]
UseSequencingMode = true
Platform = "ethereum"
RollupId = "radius_rollup_2"
ExecutorAddress = "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
L1Url = "https://ethereum-holesky-rpc.publicnode.com"
#L1Url = "http://34.47.70.238:8545"
LivenessContractAddress = "0xF05D4533801F921ae57f244EfD15B48f6E60a0ba"
ClusterId = "radius"
SeedNodeUrl = "http://34.47.85.214:6000"