[Eth]
Platform = "ethereum"
RollupId = "rollup_id"
ExecutorAddress = "0xDee97c45cd2F6e15BaDD434Eefe68b71744ebB5e"
L1Url = "https://ethereum-holesky-rpc.publicnode.com"
LivenessContractAddress = "0xf5059a5D33d5853360D16C683c16e67980206f36"
ClusterId = "cluster_id"
SeedNodeUrl = "http://34.64.123.84:6000"